export const ASSET_DATA = [
  {
    "filename": "Creature_Automaton_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xh3EsQkAIBDAwBSCgg8vTmLpFo7iCk5p7QhiYS1vOII1bH6hlzjRQ8gUoW3TP8AlpD7meAo5BabpPAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Bat_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xj3KoQ0AIBDF0AaFZIgbBI1kiC+RoAibMRIjEIK55snipYgZ0tcb6zI341ALOfj1AK7qB9jzyIqyAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Bear_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAQUlEQVR4XhXEsQmAMBBA0X8Ei5QpM08WOxHk9gqCrYV9ohaWOsGJzcOdK3IPPIEmHOl3O7GFOTO9jB0VtGCVdf8AuLUSI9kSZ+4AAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Cat_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xj3CMQ4AERRAwVds2FYhn5DQuZKjOo5SqfylaEyG5/sxAas0xS9kIJ20yVDmHSuuHpwjCBPZJRHRAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Centipede_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XgXAsQ1AUBAA0EckolLonQ3+CkYzgjGMYgwjKK64QiGw7uI0P5Y0lO7TSqQ4xKbdxtd06Qs/D1kLrllOTD0AAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Cyclops_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XhXEsQnAIBRAwRcI2Ahu8HGEVCl1BBcRLP1FiozqBBJSpLLQwHEA23JjGu7BHogSB1egdlQoH+n9zye7n/CxC/zAXWAcAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Diehard_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAARElEQVR4XhXJsQnAIBQA0UOFbBEygRAsLGwyiAvYCzqEtfM4gENkgOAM5sNV7wD04HjxH2XxKFLHZsEQqaesu+Em5vrbFR4K8Qm+IEMAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Dog_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4Xj3EsQoAEBgA4VvEILJRyr8ZvLxHMnoEg0H/4vo6fg58IF7swWx9z4xJhbZUEZI8lO0Ht9xoJvcAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Dragon_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XgXAsQ1AQBQA0BcDMML1FrgI8SfRq02gZA+VGRSGMIQhLiIwHXJRF+mRVv2mew27cRGV+MStueTT3P4v4Qzl2yy59QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Drake_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAARElEQVR4Xg3CsQ2AIBRAwYcNHZaGYPw9K7iAczCJK9BRUjMDBSMwiqWV8V8OZSr2wb2ILoQbP9kzR0IW5GMdbJ2zccUfBx0LVem0NJ4AAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Gazer_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAQklEQVR4XiXIsQnAIBQA0QMLxxBnSGnlaGJhoVX67GKwcI10WSFN+PIRrngcInyOx9INM9NuatypS9I/Au/PdXD6BbRiETjVtpN5AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Ghost_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4Xh3CsQnAIBBA0Q8pUjqAaBY5XMVF1LluFitHsDzEIujjAbwDNwmGV3KnNkpChKh8drrFs7l+M+gMQWOoGzkAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Goblin_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xl3AoREAEABA0X8KjQ1EXSC5M4BRdMsZRhCdE0Xd49M2qaMPcqAM9hIXbhIqviDyA6g2CQRKPsGpAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Golem_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xi3EIQ4AEABA0S8pNpvsEKIjuIlGozqqJJokY7O9PQDZP9Gok5LuTxwEQ96PXiiH9QdNuw5KtntaOgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Hand_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XlXGoQ0AIAwAwReISiRJB2C9ykoE43UYJKKCpI7Pi+Nr1L3sYHDQy0xaIBtZD0u7BjP2AYarAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Hobgoblin_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4Xj3EoQ3AIBBA0S/q2OHaKcDcDixCguREZ2MGBiEIRINsMDzxOELnXriGGKq8lTIwIX/EuU+e6/kB86oMKuAGBvoAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Horse_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4XhXGsRGAIAxA0X9p7PDOGi85FoANdBrmcLSMY5EiI3B0D3k5PopzJprcTh0o2/rzBD1ok2ZchtgCB3IKaMnUNIsAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Ifrit_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XhXEsQ1AUBQAwCOC6ucVJIZQGkBiCMYwmhHUpngxiWgO6tCumluVulQu4ykmw/Hbh2W2P7aX+ACm0geybutBhQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Imp_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xk3IsQ0AEBBA0Z8oiEgoDKHUuyFsYmEDKK9Su9IrHz+n+ENWUidOQqE2xkaEdS1tHotWBxQnWD03AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Jelly_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPElEQVR4XhXCMQ3AIBSGwW/407V10DcQJhIcgC0EMCAASShACRLIuxzug8e/h39Ql88dC0SRhE1MFNH2BZZ7B346WzpGAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Kraken_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQUlEQVR4XgXAoQ2EMBQA0CdugD/CnwGBI+kGJ9GA6AD4ToZiDiSKoDoBgQyRYpU/y23r6qke9qZ006O9/sU8GK8P9SkMuyxRFfwAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Lion_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XgXAsRFAMAAAwG9EkxFSKVIYgMZJYQATUBnKcMZI5VzOQQi6V98M1fbZo+N2XtaqROUxJ1OSF3n8AQH9CmdYpV5rAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Mermaid_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XiXAoQ3AIBBA0Z9UnOwACCSWpAJHF2AgJkRXIhEI5MkTiAoehwxuxRuu8xq5khbPR4n4SWpIQDaX/hJODKB+HQnyAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Mimic_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4Xi3EsQ0AIAgAwS8MUloykVO4BQOwkKWlw4nRz+V51UERELTf+yLSJPYHaMPsAJ0QCEYkMPJuAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Orc_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XhXGsQnAIBRAwVco2CnYfzNFcAsXcATBUiHLOE6mkZAiWAab4wCMw9+EhX3QYydmLqFNulA/0rstJ+r4ARFuDL+j7tpCAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Rat_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4Xk3CoQ0AIAxFwecqEJWwDVugGYXRGANNOsIfgNRxOX5tZl+MTb8QmHBRhWXKeac/Cn11gMYKAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Reaper_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQUlEQVR4XhXCoQ3AIBBA0T8CG1Ueogkhl2ARmG4AI3S0joBEMMBJBKIheQDFqINgeEd8j/SgH+ppjmuRNzIR4+4/SfwPCPlkvtgAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Scorpion_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XhXCsQmAMAAAsIBD6yJFCoJLHfuE4NgT/MXFwxy8RDxFhMBAYSJt+pNFd4tJeH/r5Xjsszaq+QN+8wdBtqiaiwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Skeleton_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4XiXCsQnAIBBA0Q8niI22V9pZSxbISBnEwpEcwCFSZABHMIePx+Ff0rKh2/ggA7lRpXzUxjVx+b8B0OEI29IcxngAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Skull_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XhXGoQ2AMBAAwHOYJkU2zQsc63UIxuswL18CyYmDi8Wdeokwmti/+b30dDxwwgvAzge7jIdp+QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Snail_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPElEQVR4Xk3CMQlAIRRA0QsObiYQBN0MYgJTCK/B52MeIxjIDA5vEDcPh5fZWL1dQSYyyI248D/hI3WqHro2ClhA59XlAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Snake_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOElEQVR4XgXA0Q1AMBAA0CckhI/agDGMYSLtaEYwSge4XAQ0pbmooaYjeQxpDtundOtt2U2n8f0BCwYLEDTwiSgAAAAASUVORK5CYII="
  },
  {
    "filename": "Creature_Spider_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XhXGoQ3AIBRAwSe/afJDBSMwBAsAkgXQXQfBHIzBEJWIzlAFJCcO4B7YDze386dRfq6Of4mVnDABFUS3BTCiCxEUFr2zAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Creature_Stalker_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOklEQVR4XhXEoQ1AIQwA0UsQRZAUgWAEJJsgWfyLLysYoCNQXi5HSI4Y6uRKzbQRf4XZ2R/roIY45b+vVwjmHUqg5wAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Wolf_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XhXCsQnAIBRAwUeCXxCXECewtHIVIW1wBTewctAM8AnqcQAiGIf9uZX48ij1o026p+iZB+kisC/1tgqdJIDbKwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Creature_Zombie_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XhXGsQnAIBQA0eMjiiBYJrUDSMpsYGtnmxEdxcIBfpEBHCHxuOKxEw4lLvz/2MidcGES90mblBen2AepH+pgCk8jUYg2AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Emote_Angry.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAANklEQVR4XiWKsQ0AEBAATxSiUChti0phAOMYhUnefyRXXHKHiHEC21OdsRKzMKJ5u/Rs6YR/PouuEKDlxqhUAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Emote_Excited.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAMUlEQVR4XiXKwQkAMAgEwQtB0nYgH8vSToRUkAo0hzCPfSwyKRZsYg9SaezzyO8f+iybpRJAvGZ0ngAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Emote_Happy.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAANklEQVR4XiXKsQkAIBBD0YiFXOkA7qpWDnHDOIpOciYIrwjkI0JOwc7oSbxhGWnPinF5MfjlA4l9EKA5wnXZAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Emote_Hurt.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4XiWKsQ0AEAAEbwAxAotIjGMArbCtAVQKEZ7L53PF8fGTuGhbS4Pc78uro1iCUSA4WxkNWlJKK78AAAAASUVORK5CYII="
  },
  {
    "filename": "Emote_Nerd.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4XiWKwQ0AIAgDu4mb6EYmTMCivpiCByG2ernXtfiMxCp4S7KPtIBPlVU6PC5G9w3A2CKelwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Emote_Sad.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAANklEQVR4XiWKsQ0AEBAATxSiUChti0phAOMYhUnefyRXXHKHiHEC21OdMQsrMaJ5u/Rs6YR/PouuEKA8dRH5AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Emote_Serious.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAANUlEQVR4XiXKwQkAIAxD0UgP4hDuKnjpEB0mo7iCE9QG4RFy+MiU00HDahITPor+vlpaBb98jCAQoBKp7AwAAAAASUVORK5CYII="
  },
  {
    "filename": "Emote_Sick.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAMklEQVR4Xi3KsQkAIBTE0BMLa3ECN/WDg4mT6CQnASGkerLpFK2skX6z8uiKy3cDIP0AiJIQnj402qYAAAAASUVORK5CYII="
  },
  {
    "filename": "Emote_Sleeping.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAMklEQVR4Xi2K2wkAIAwDI1KcwW39cIiOo5u4SU0fcISDHMycN3A6Viu2QGf45fJikOUHhLUQTcC2+IgAAAAASUVORK5CYII="
  },
  {
    "filename": "Emote_Smug.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAANElEQVR4Xi2KwQ0AIAgDa3z4ZgB21Q0YgGF0EzbBEk3u0eYOmUUM7I7ZPq4wqbF4DxWDV16F5hBuXculTwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Emote_Upset.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAOklEQVR4XiXKsQ0AEBQA0ROFKAxgW6JRGMA4EotITPAnwI/kFVcc56jlGJZkVA+0SPXaWSjC3G/45wWg/RJ08O/ydwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Emote_Yarr.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOklEQVR4XiXKsQkAIAwAwZ9AR3AIW8FxHMDCJuBuGcUpUoQg4hdfHb9sVEeC3RjKVNZhB5Leu1PswwtK3w35LsoJPwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Altar.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAALklEQVR4Xk2JwQkAIAzEcri4e/hxk3aNDlNqQR/CcYSEKqawZOtfy07vY+Hj8gGOohEVRU6YwwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Beartrap_Ready.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAIklEQVR4XmXJMRUAAAiEUDYTWodApjKKz/kYWD5Z7b8HTTxC7ALjWUPefAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Beartrap_Used.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAIElEQVR4XlXEsQEAAAQEscNiRjPaj0b5UgSXovp9YjALWhYDkQOdBx0AAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Bed.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XkXFsQ0AIAhE0StMbNhBR6CjdP8tGIABKCg8Y8HPyx3YdFg8e2AlTjX2V4X4Fy2wCwi06pSjAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Block.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XhXKsQ2AIBRAwUdhQckIjOJmfiCBDjaATYyjOIKlBfmE5MpDlctwT/pP/cgv8UFkCyfJUxzNMo7dVBfcDhHCvHDjwwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Bookcase.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAL0lEQVR4Xi3GMQ0AIBADwCIOCcj5BCsMLI+IV9Y8HZrccOjGHlbEIzL8O8U/S/QPpsMQyJuqOoQAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Boulders.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAOUlEQVR4Xg3CsQ2AMAxFwWelcIUoGIBZvRqT4MgDuEwR6YN0SKybPmnndVJMpwZ7UMZjxO8gLiKRPrb4EU6e5WYmAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Brick_A.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAIElEQVR4XmXKsQkAAAgEseMn+f2XPAsrEVKG9lCSD90whCQF2Xod/kMAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Brick_B.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJUlEQVR4XlXKsQ0AAAgCMOIlhEf8/ylxkMWkY0E+NlTRAynsCwuvfAgyjOHeKAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Brick_C.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAIklEQVR4Xl3KoQ0AAAgDwYYu0v2H5BEoSE6ekgPkluuDDQOgQAbcx4DGIwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Button_Ready.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALElEQVR4Xj2JsQ0AMAjDMnbsFMa+x+k5gZEiBFYGy8HyAvfAVKODav+xriEBuHsH1yMl1rEAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Button_Used.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALUlEQVR4Xj2JuwkAUAgDU77yQQawdTRHdwRLP6DHFeGCQwL/tfRRQatRpa8lAY1gBh4QtVDkAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Cauldron.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XhXGMQqAIBiA0S8I3Z1+HMSbWA02tjZ6DDfDk0ZHcBYJtwegX0TwK/FgM+x1+racH0mRHWUQOldjeX63CwoOUkxfwwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Cupboard.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJ0lEQVR4Xl3KwQ0AAATFUDZnEyxiMvkinCTv1JSAIfxcDCfTkbVnA5iUEr98bCDCAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Door_Closed.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAMElEQVR4XlXHIREAIBAAwfsoDAGoiCAQggh4yrw/DIaZNYuSjV0Z5TODI+sVpQd6AX9eEF161TIwAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Door_Open.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJ0lEQVR4Xk3HsQkAIAwAsCBOIh0dSun/ZzoJQpaATT/BIamvi8nABR0CAROSzSfFAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Flower.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAI0lEQVR4XmXGwQ0AAAQAsSNhLqMYxShGFV/6KocU1niisX8GOx8CUNaxHNoAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Grass.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAHklEQVR4Xm3CsQ0AAAgCwY+VYzsKo2IPlyPNF3s0Bhv2AS2S5QHTAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Grate.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xj2KuwkAIAwFDytrB8gqWmajlC4ukk8ReBwH9wDGYSn7BXP2SyZXgp3yBg61NgddknXG6wAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Panel_Ready.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAALElEQVR4Xk3JwQkAMAjF0NAROlEHEBzJnR3gUz5ehHdKAEq8Y9kWd3OZWwI+7PgJnFjG47gAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Panel_Used.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAALUlEQVR4Xl3KwQkAIAzAwKOTdY6COIr7OKIPkX6FkEcIrCvDPM0otT93z+iNB0aGDXJvBaZMAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Pebbles.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAI0lEQVR4Xl3JMQ0AMAgAsGY8k4E0pCIFKfz0rau9oXwihWMBPRECMcFy6MIAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Pillar.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJElEQVR4Xm3EoQ0AAAjEwBoMhtUYkRF/BAgGw6Upob9hidd9NTn1Cky7HdPDAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Pyre.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4Xg3GMQ2AMBAAwAuQtAvMv1EHlQBSKgEJyEEWIhgYGOhyOci7oRmLdEq3+bBcIotQH2Wyfda3p/sDnzwIk3WOpCYAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Sign.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKUlEQVR4Xj3JwQ0AAARD0bo4mtEINmByoZFoXv6l2Ekhm1zZMPbc+4ABSSUMWODD0PQAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Slot.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAALUlEQVR4XlWKwQ0AIAyEyE3Wh8Y9uoi7dpDG61PCi4C5TYhTrGT/urjb0GzwAA4XC4l8EfPaAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Stairs_Down.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKElEQVR4XjXKQQkAQAhFwccGMcuCsTzY1CgiwhfmOADZ/HdMvCRkGwzvGAxJCUpG/gAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Stairs_Up.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKklEQVR4Xi3C2wkAIAhA0Uvt4SyNFfTRbg7iKCI+4ICMbeM1TXelU74DAf8yCx+P6sYlAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Stone_A.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4Xh3GsQnAIBBA0Z/+BrhhbrmQKQRHUTiwEh3AUku3CNo9auYNAOLEjgqP8y3apsxjVdLALtx+cLcPIi8LduAAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Stone_B.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAQElEQVR4XgWAsQ2AIBAAbwVjRYOOQGUJwUmsdAUqdiO/yCdffMsGGK6b/mKL4VRhCOa0TIqcB7qjG09AC/OjyA+dCBBRrEfQmwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Stone_C.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAPklEQVR4Xh3IsQnAIBBA0Q9ZIKWCELubwcqgU9kdTnaYImvcKILtIy/ehl6ooAUf3D/PJE+sH0xowCIu1G8DII4Me56ARn8AAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Stool.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKUlEQVR4Xl2JsQkAAAjDOuki+IoneboneIJ1E0OGQPDQgjfdIJKwuH8AbngEbyZdNnQAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Switch_Left.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAK0lEQVR4Xj3CsQ0AEBAAwCsUCoXaFiawiv0nUHwhEVzON89KJtGWXoy4nw1r+AXd//hpHgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Switch_Right.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKklEQVR4XkXCsQ0AEBAAwKtEaQNGsIE1DGXkLyRCXM6XzkyhqVNfRtzPBlDpBSnipDowAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Table.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAKklEQVR4Xl2KyQkAAAjDKi7uZrqBw/gWD/wJoYQSVMEYQo89NWc38DjGG2kEEkzOJGE0AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Tombstone.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMklEQVR4XkWKsQkAIBDE0lnaycELrvEjOYLjOoKlpcoXhpAqBGmSF21T/VW6/dqg9BgP8kAKBilw5boAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Trap_Ready.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJklEQVR4Xk3CsQkAAAgDsCLi5OAJnuBJ/n+FFJeGQFkhhp83clkcHhgBewNRCZQAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Trap_Used.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4XhXKMQ0AIAwF0QtDBSABCRiAEMKEiAb/Ejrwm7zhhgMYgRuzsCqnizrtxn2S7ZYbfKr7B1HfH2faAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Trapdoor_Ready.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALklEQVR4Xl3KIQoAIBTA0Jf+tewWwQv47x+NYpBfhYXBBu3KMLbZi3U+qZRRGw8hhgwfDg3EzAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Trapdoor_Used.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJ0lEQVR4XnXKsREAAATAwJzCWmxgBfuXagUGkEv5ANak4vIeteAYDJcYBta5pldbAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Tree_Bare.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xj2HuQkAIBDA4lPdDBZ2rmDpCDeBg1zlaA7jIHIIhhAID1FypXRvHNikHdImrK8vXH/IBqZTjrC+AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Tree_Full.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4XiXKwQkAEACG0U/OMoI9HFjEKIqRjGAkRwdJf+odH4Cd+EXY5CPtSk3EghuY/qnBA0uVDJ2HxTOKAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Feature_Tree_Pine.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xi3KsQ0AEAAAwROF0ghGsZrRjGIEpUKBRPL5fPEQmtilgec8lYUfdf/nwgHjaAl8Pe4l7AAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Waves.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAIElEQVR4XoXHMQ0AAAgDsApADAn+HUwUBwLoV6diGm8XWbsDsr6/CJoAAAAASUVORK5CYII="
  },
  {
    "filename": "Feature_Web.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQ0lEQVR4XgXAwQlAUAAA0HdQlIv0c1b6RRydTGAIA1jAJkZwNoUBHAzwRxFUrTIJi/px7KbTeImfYdbcutXWy19ZgR/T1AiYjFpjrQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Feature_Wheel.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XhXKwQ1AMAAAwEs8eBA2aGxghi5kiBrICKSDMIKXSHya/g/Gx9SZNzHK2Zkcjbu1D67f+lp64auMAiODDQNS1OQ3AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Archer_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQ0lEQVR4XiXAMQ3AIBBA0T+1YxNWBmSwkHRhxwFDJWABUTioAgSQU3A5BQw8jnvxKEHxk2DUxhD6T04U4xWicH24vAEoQg1hIWX4PQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Archer_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XiXCoQ3AIBRAwadaAck3aBQTYLoCW5CwDJLlGKBBoJuvKgnhchz3i3y76YhiI02pk+TJP8/Yr4ILCxNEDIGaUGx3AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Assassin_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4Xg3IMQ5AMBQA0JcQmnTQRGLlFr2O0VGN3MAshr9bWB80ob8MIRUlGXfTJh/aRT7Nr3qrj2795QPj5Aomr06p1AAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Child_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4Xk2IOREAIAzAcleeATYMIKGSKg0pjIxIQAp0I5fLEH6q0hb5EIc3GbIJnTIR980LiAsIIFPX9DoAAAAASUVORK5CYII="
  },
  {
    "filename": "Human_Child_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xl3JOREAIBDF0AzLUVBgBQlIQRpSVgISvhRmW1KkeXyZ00Q58bqxS54M0T0orQd+4Qdj6pf5PQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Cultist_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XgXAsQpAQAAA0BfKFeVKmQwmg8kok48wGg0+1egzbrxPEJRZnXRZiGLQv4ZH86km42a+7ZflVBza9QfK/Qfal0FEDwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Elder_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4Xj3EsQ0AEBQA0etEpTOHzgRUBpEYwRJGMICRfmEAhRFEIi4vx09NzH50u7cZv6hCEcIgdpI76c0MD4cRIr0AAAAASUVORK5CYII="
  },
  {
    "filename": "Human_Guard_U.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XgXAsRFAMAAAwJcGjdwpDGAGEykc0qVUZgTTqTVaZwJHUBX1I77ipz01vS4L2bFYB+mSbluxz6bxB/GxCxgjviEgAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Knight_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XiXEoQ3AIBRAwRcQSAZAsAVUMgmp/wuQLtgdqn6QyMqKhhBOHJtT/Ev8CM+6XuSBvWkH8iMdUdKJKRMhFw1czsbCyQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Knight_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XiXEsQlAIRDA0MD/YKFga+kMFs5jfws4pxMcNvYOIHIYwuPllLhtP8xQzG/RE3KQiSi18ecLBi8MPL3lC3IAAAAASUVORK5CYII="
  },
  {
    "filename": "Human_Lunatic_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4XiXKsQnAIBBA0U8CphEygMVtoSIWmURuYAewvBGutAwhr378LuN2ZJE20hidrJyTWBGn2BeCcjwv5tAKQp3oXEsAAAAASUVORK5CYII="
  },
  {
    "filename": "Human_Lunatic_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4XiXJsREAEBAAwcsEfkg/0IfIjFKUqgQlfAGCL4Hhwj1+wchOXkQngUyaUDeq1981yoB+ANlCCciicLTSAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Monk_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XiXEsQnAIBBA0Q8pbISDtIIZ4zpHcQ5xQIewkiutxNIqhLzi8XMDWTyH0L9zRSdXwydiQQ1unCH7BQWdC8UwgHBKAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Monk_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4XiXIsQ0AEBQA0eu+hERigD+DaGxnSBP8KNRiAsQVrzh+YsRF3Pj+DOUpE6dooxo5IePOA+yICvduNifAAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Necromancer_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XgXAIQ5AUAAA0FdsojsIboL2bTb5S9zhX+kfRBRFwQFMEgQTmV/1p7mER18ZSuNmWi2ntEuHImuzLgr3D14qDxyS8JVXAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Normal_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XiWKsQ0AEAAELyQ0EgMorKDTmkTMYTpjKA2gUCoRX3zukuNPD+zCb1x/nytxIhsmXL38AlUQ6QANsAvLSCm6OAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Normal_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4XiWIsQ1AEQAFrxAkJGzACDrrGNkIBvjFL5W8uFyuOB5ukX4ZphrbrabPlE3/pB2YegD0DwrhiuGGGwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Phantom_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XhXIMRGAMAxA0T+QS9h6Ze8xREYEIKkyKiFyKiNSgO3dA9DCGs24D9wpJYWnE8G1v/w9B+dC8gWTTQcPlx4WHQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Phantom_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xi3EQQoAEBBA0b9QpmwkZZaWjuJKLuNMjmDpGEyp1wPwG4lEMbm9P1XKoTp6MmMS1gViDAWti2ezawAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Pirate_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XiXKsQnAIBQA0UNBEdxAyF8hna2TSMrMkEn+OBnFASxSplTxqlccO98IH8dNUkSpD7ljX+KJ/NNrcBemDOc6CpTay9RIAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Pirate_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XiXIsQ3AIAwAwS8iIgSC1mW2oMwqHoFRPCIDUHgACoR4XfXc3kF0ipKMauRO9TNF+BdtHkF5vg3XbAom+CBiVQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Priest_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQUlEQVR4XhXKsQnAIBQA0SMBbQQHsBBc4neOYvHHcECHcIFASiuxUq+46nF7sB9+EBeh35eK/LwNl4kTUUzC6jEbB4MLZ+THNUYAAAAASUVORK5CYII="
  },
  {
    "filename": "Human_Priest_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4XhWIQQoAEBAAJ5dVlB9QnuDAd+TJHsHdA8RO0xwGxSCbcFQ3tb5oZWEj6dI6NSPjzwfubgqZToD/HQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Ruler_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XhWKoRHAIBDA4pAoFNyxA4hWwQKM1IEYhgGQDIBAViB4chERATAVvQD8j+3kTfp4JrFRAu69rYYo2wEPTQygWl/rRAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Ruler_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XhXJsQ1AERgA4aveayQGEIxApbGMAQxgNKMoFEZQKJTyJ5drPgDb0RuQm4G/uEY4/Is8RVOVvoKKDwzwC1ButUMNAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Thief_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XhXIoQ3AIBRAwRcEH/chhCAZo7ajMB5jVHaMSkIq6jFQdzkAvZAH/XCe1MideG//6QJlcgzkxVbMuQDvCgpTO8CczgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Thief_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XhXIoQ3AIBRAwScI4D6EECRs8dfpeIxR2TEqCamox9C6ywHIibuRFx/InTJI1+c/faQudKIP9sC0DfBuCmW30anKAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Wizard_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XhXEsQnAIBBA0Q8B0xxkAMGsYHddRhHHkAzoBvbaWllbycHjgZh78CzejW92+tHJVZGPUNCOy0biAQi/CuPISuhcAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Wizard_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOklEQVR4XhXEsQkAIQxA0V+dBwbcIDOIha6TSdzSXhtrcQIJPB6IC4t0SJc4fCl+2PyKdtqkGp8h+QHwtgofd4GQfwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Human_Wrestler_F.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQklEQVR4XiXJoQ3AIAAAwXc1hKYKQ9IVkLhOwgywQS0zMQ0SiSIIQmjD59yzOzJn5e64xDOQAVWwmnfiG1f81k+YBRmMDQbkDEyyAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Human_Wrestler_M.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPElEQVR4XiXEMQ4AERQA0ek02Kg0m7iC0q24gdZxHEmp3GqjEvkxeRluavB8wnS5LfhJeqmb/OMaYQkdDwRWDFhRS3zvAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Ankh.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xh2HwQkAIBDDCoqu4R73cBVHdZB7OIgPU0sIqVjZ6kd1qC3Cd15wRGLDvh/4SAp4wppj5QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Arrows.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XgXAsQ2AIBAAwMMQGzo7ChLjEF9b/jTO4AhUzEtAcJEs5XGkOvVbvL7foHFSYQNkzgP34Hu5CAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Axe.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XgXAIRHAIBQA0HcTKMQkEZCEWJCfZpIEBEEShQhE4ABeKh8/3TOkKR9la0sQgAuG5AaRfSmbbAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Bag.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xk3GoRUAIAzE0DgqmAADa4BhFUbtKIxQeRJw5EV8/pKTF7YfrFGCIbqY96A6cACniwm9Fi8yggAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Beer.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4Xg3EMQqAIAAAwNsarV3xGa6NIj7Fl/TKntAUEQ0Jx8HOcgmP/MrzT7hth9ikqUvVWJUTPwVqClhr4lBEAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Bell.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4XgXA0QmAIBAA0AeF9iVtEKE4x43WqDfCjRCgMThJR3nKLG9aaYc7XKF/wA+yxAeYHPDG4gAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Belt.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALElEQVR4Xl3JMREAIAwEwRtwRQNCmBeSN4eSKElBy7Dt8pnFajgJYTE2/fC4h1wF4ecK1FsAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Bomb.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xh3EQQ0AIAzF0KJgKCBTQOYADhyQxXGyyV/zUlTApaVuyTgsl+l46Rt7VB90mwSushM66AAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Bone.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJUlEQVR4Xl3GMREAAAgDsRdQD1ioA/w7YmDgWJspJGHRQ+3HhANHRwMHCbqS0QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Book.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XhXCsQ0AIAgAwU+0p1QTElZgNId0IApKC+VyFIegBeKoMzcrsf9gHe2MrHKBB87dCY5wbZdXAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Boots.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALUlEQVR4Xj3KoREAIBADwSjKoJAXqQRBGS8yqR1i/mblYaLitzvWRR3YIc71AIz6Bk/5YSo+AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Bottle.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4XiWJMQ4AEBTFmnjBJMY/GBzBaHAYR3UURxE0HZqUj1v4Sdg3VEmZEhmiP5swuxcOgWMFPfMAhRQAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Bow.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XgXAsQmAMBAAwFPDk8LCyiqN4CgOYZlNBHEQB3GAlBlJoIbrNjVbt7zyKX2GYpylRz7YWQn8vI8GM9HgAVkAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Bracers.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKUlEQVR4Xi3KsQ0AMAyEQAbyCK5+oC+ZP4pkdCVcA0IZsVQMDS7h2/senEgGVUNN410AAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Bread.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4XgXAwQlAUBgA4K9+xc3BXU6uVrCBEVjklUEMI4O8ZAoHvQRxik19a1/9Z8pSsT6Wy3joBs2s2gX8IEIKzR31wqoAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Broken.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4Xj3AIQ0AIBBA0c9uuwgYNhQlcEQ6iyMBEchGAMRJJI7HJ4NgFMcUVeKkZWzRD9VJF9nAA6KTCR+H3izbAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Candy.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XgXAoRGAIAAAwPcMRr0jaMMRjNxZGIloZAQGcggHMDiCI3DgIBlu42v6zL/4WJuwsCvZVZ1s0AHCUQe//pkMMQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Cart.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMElEQVR4Xj3HwQkAIRDAwFlf99KrwJrsyFatwBJE9mMIgXjMQ/GllNzW1Z2NIX4WLniABasOE4rEAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Chainmail.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xj2KoQ0AIBDEOgEET8IaiPudfgyGYigkEt5801SVRMJ2tE+K0xbjhkA9eT2VHgaCubnTvwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Cheese.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4Xj3KoREAIAzF0DgcKyC7AYfg6OoMwDDIii9ANfdkyArUTbu46JP1DSww4SevB6sLB8/sVhClAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Chest_Ready.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKElEQVR4Xk3GsQkAAAjEwJRu5VCWFi72gziOIAgeKcLnTYkQBrlT1xnSJwmhtVKd3QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Chest_Used.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAI0lEQVR4XlXCwQ0AAAQAsXsIS9rCABYznIeIaMowR/RGkf9ql8gH4lMYPMoAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Cloak.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4XiXGsQkAIAwAwQcFUwhmAAVHsLTI4I7jCBlBgnDFASSnXJojisoXz5NxMAu7syrwAJ5uBcs84zAoAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Club.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xi3KoQ0AIAwF0SMVld2AGZB/PAZgLAZBMAQCQUh6efLIDuV+trGJD1zEIjoVBC2/B9MKB3frpOi1AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Coins.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALElEQVR4XgXAAQnAIBAF0JdgroFNLtkHxWQmOwQwtnnNbcTfviYcoo4Vi4IHymsIpZxJBKEAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Corpse.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4XiWKsQ0AIQzEfCBRMUAKhqD8cRglYzDml5QQ5WSdXJicfupBOyjPHTPaQh7/DWbP8AK2rwah4h9//wAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Crown.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJElEQVR4XmXJMREAAAgDsXfCsbJiBUnIQ1BHBDRrcLn0UUMI80tJAzrPLOmkAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Crystal.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4Xj3KoQ0AIAxFwQcJCQnmKyphFEZDMhqjMEIlrqePkJzslEe72MEqXWiixdixPpwHBbd7uflcAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Cupcake.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XhXCoQ3AIBRAwUcQYBpY4M9QhwVZ2YEQjMMISEZhgIoKBiD/cqiCadhJ+JFOquQPGdyb6JFHXy9uAQffmwlEAT1ifgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Dagger.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAK0lEQVR4XkXCsQ0AEBAAwEu+0KlF2M1oRvgRjEbncr4m3s0RS0k1TToDgAtcJQPCmRFP0QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Drum.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XiWJoQ0AIAzA6liCYI4Zwv8fcAYnIJFIJAOq2hRABVHCIHZKo27SIk/M3H/e+zjh+woh0DVzZwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Drumstick.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4Xh3CsQnAIBAAwIMMkNbqZ9A6jZPID+AAqcTRHC0QOFCIXyVdx50eRre6ub1bI+ADdewF4WxT1kkAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Egg.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4XiWJMREAIAzEcteBEQWADaQhDylI6PgjtOQyJXxsUw7VMadNusKxUr0eN7nvqwpJqR6ZXwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Eyeball.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPElEQVR4XgXAIQ6AIAAAwNsoNpqz8QUTo1l8ksHAw4xGn2I0EAgEBwi3+Fm6+ZSr9VBe25Au6RGbsDPhB/M5CiLLSppmAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Fish.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4XkXCoQ2AMBAAwFOYBt0O0wTJGnUYVmhYiRF+FEaoqibBcDm/YjmtUxryY/v2cIX9djQVXspWCjRiFWJ0AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Fossil.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xj3HoQ0AIAxFwbdJEyYAV0NYgZGQjMIojFP5JUHAueOzQQnyxDcm0sKhdppunwPF5Qht81iYFgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Fruit.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAL0lEQVR4Xi3KMQoAIBDEwIDgVWK7lX7T5/qELS1FzjBlyCoEFGhmLCTm+bqf2DleknIH/ho22jgAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Gem.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALUlEQVR4XkXJsQ0AIAgF0ev8CQ2JBStbMhZjMIqxUF+uO57RWBL1mwsX8rOuDapeBrG0dgj/AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Glasses.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJ0lEQVR4XmXJMREAMAgEwesSEXihRRJ6kPZCGHrYdrm8SRHiF89WDm4eBI8RHRklAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Gloves.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAL0lEQVR4XhXCUQ2AMBQEsIpABEHDfT0Ns8PhDGmErCk4ufbjtT5r3PHUVEajDIEfu38H4cTDoFMAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Hammer.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4XgXAoQ2AMBAAwPtPQ1BM8CMgkFWdhREqq5iNwRAEvOKUpe1aySEePttyXIrO5IYfcQEE0+iKA5sAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Harp.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xh3CMQ2AMBQFwMPCw09ri5EBKYwV0LFSvgQkEEgOGp3tlCWHXHLLkPl7PnvphRfFkgoPBf+9PwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Hat.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALklEQVR4XkXKoRUAIAzE0PAQlVgGrTiJYt4THQAURER9fhMSima6CTPuFxKxHzqlnAdf90x/WwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Helm.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xj3KoQ0AIBDF0KJAXHLgvmMFRkQyJiMgkRhyzZMlyhs/9PulSVvUgoSNuB68bwbKfSOX2AAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Herb.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4Xh3GsQ2AIBAAwPto6QAEfglapv9RGIAhNCZXHES5tnFketp3URBMFp37xwuprQU6tUoaAAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Hood.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKElEQVR4XkXKsREAAAQEQaGMCmjkC1O2UGgk72bDE2YtOc/1RB2A1wLATgcwJ5ulNgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Jug.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xk3KsQ0AEAAF0RM/rCBRMIaKVYxiNGMojYLO5coHYCeu4zdxkUURVbTvFB4wAzifEQXQ/IYhGwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Kebab.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4XgXAsQ2AIBAAwIsWDkD7lYMQEwsahvghGMPRGIQRKA04GGzC+bkmS6Sa2uOlcNPhB5/HBjq4QY8PAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Key_A.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJUlEQVR4Xk3CsREAIAgEsAxh+RXuwf5DUXh25GILTXHnr+gjtgdQNwNnpdDFxQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Key_B.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJ0lEQVR4Xk3CoQ0AIAwEwFNN6pEs8lOw/y4IguvlTEUTzv2z9VKmB06vA1cv8kieAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Lantern.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xh2IwQ0AEBTFGiIuNnFgBNtYyyiGMICTCQzgfU0PTRF+4hphkCrlEjeiH4WZl77F5wHaYQku0weANQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Leaf.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4Xj3CIRHAIAAAwL9NzLEIi0ItBMGQxEASAEEEJjj+3nYx3M1TvEmYvn8Xq0h2LMH2B9b287n+AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Letter.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMklEQVR4XkXGsQmAQAwAwOuMKNhmG0dwkR/+yxRPECub42Bb9na04CoRn2f+H+kp98QL8LAKdmc0R3sAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Lute.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4XgXAMQ2AMBQE0CcBBXwHzCQMIAEbbE0YOlJpJ6VSCFjYWNlpajrjG97LHU/0OIaCH7ASCP9HR3mtAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Mushroom.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4Xj3CoQ0AIAxFwZdUdAUSBDPgcKzGGIzBaJVfEiq4HJ8HTUwxCn1TD7Zez0biAruMB0HcKw/OAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Necklace.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xi3CsQkAIAwAwQcDFgpaBmzS2TqqIzmGA2QQET2OR5XumNwj0zbRKPNPFTHCAg59BgW5ibhAFgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Nugget.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xj3JsREAEBBFwZeREZkRmN+OUpSitAuVILwyjIBNly9s0kKOBs2ohialE/Ot5wC00gcfrHOGJAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Orb.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xi2KqQ0AIBDA6kCew14uJEiWY4gbhFEYhFF4m7qWR5hEITl1fEtHG5YR3+kMlwW9nAe0AtUUZwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Pants.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJklEQVR4XlXEMQ0AAAgDwTpBAgaKc2QxMJKGBT6Xxxape4k1yOc0ve0Gr22zS/0AAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Pickaxe.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XgXAMRWAIBAA0M85uGmBC3JxjEAABiejMRGFED64X20zKJKlTcfnDFfIUHQe+AGawAWo6+KVvwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Pipes.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJUlEQVR4Xi3GMQ0AAAjEwArggyUk4F8JIwl8c0P51OR4VAcL+xZUygKn7hJshgAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Plate.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4XjXAsREAERRAwXfjch2gDvPRiEIEAoUJlCQUCATGcqnB7xDBZ0InVtLGFL6GXejJcwC7RQgR5fsnsAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Pole.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALUlEQVR4XjXIsQ0AEBAAwJNPRGUCQyiNYwQj/GhGU2kPVDqDxSSVK1LQPh82PErhA4whuH6QAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Pot.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xj3HIRIAEBQA0W0EMxzAjCPQaO5/CwcQBEH4gV/svLL8zMAVlQ510iJdHt28CRa/gAu9zAm1yjffJQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Ring.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMElEQVR4Xj3CsQkAIAxFwQcJYiHiAPondsiMYGkppPA4vh7ooMvamCNn5lYpAwvSA4t9BTJl543qAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Rod.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4XhXCIQ0AIRQA0Pd34hwJCIIgDBGIQwQCIhAIxvYAtjhiPJaovuknkSl0GlysggY9ypgWuAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Root.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPUlEQVR4XgXAoRGAIAAAwBeq5wIGR7DqHXc4jtERGMVBDA5kIBIIHoTNfNlPaZS79ZE/SzNV8TUU8RBuCn7lmQm+95fMJAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Rope.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4XhXKMRGAQAwEwKU7C3SBCUJw+JKQFAnMb71gHPHGFbXUqM89ml6eOLODwQ+xTQc9bU3VdAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Scroll.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKElEQVR4XmXJoQEAEBQFwBvhN5ENjGdtQXpJEJUrB/NY0WKAKn0//73yggnpftbBRwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Shell.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XjXCsREAEAxA0d8pjZA1FCGrGMVoRjCCEZQpcc67xxMb0rFJqeRzoAnzW5yw+DbpxwnGM/gQ0AAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Shield_A.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4XiXKsRUAEBTF0BSv0LGBFZQK/OWMZhQDKJUO7kkZPr+IG5vYoInab0VkkURwd3gO1jkHyNlRQmAAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Shield_B.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMklEQVR4XkXIsQkAIAxFwVcEbBzAzhUc4Mcs56ApHEQEQbjqAEZFIjZhj69r2p/eKAkcmhQGTPDIgdEAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Ship.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XgXAsRFAMBQA0BfuUGQEeyg1uZhDZQv+CEYwmhGUKR10IYU+jGF5HLdtUgcl22dnc33WF/gBzF0JSHuP1A0AAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Shovel.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALklEQVR4XhXEsQ0AEAAAsK5WMVh8Im5ygOA0pzhFLAWZRKTRucJRtspi7e9kwAN/5QZmKBX/6QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Skull.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xj3KoQ0AIBDF0A5wCRJFGOIM7lZhBEZkHOSXSEJCaJ4sv9TJIjaxsIG1y4VPKpR3HbIIBytTj8FnAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Spear.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XgXAMQ3AIBAAwPt06IYCpqpADkEBKioAWchhZCAE4ojNovExxPT8XhKZQqfCBcC6BpAOz+MAAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Staff.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XgXAMRGAIBQA0PfVO51IwGAM4hCBkVCODAQgFoMHHoHOdi0xxOec7kMivwqNCj+OFQW+AyO/PAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Steak.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOElEQVR4XhXC0QmAIBQAwCNC3MIVHCDogYJrtEngZI3VR0QEBxuNuEQV2Vj1qU2xOJLz/e2PcuMDvE8KAq/xEa4AAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Sword.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOElEQVR4XgXAQQ2AIAAAwHM+/PDnwcZMAT9mFDZa+DKCsQhCAhM4kGncfLZln45XPZVLegQigw4/onoGXpu7clkAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Torch.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4XgXAoRGAIBQA0Kf37yg0C2MQiY5CZARHcTxH+JHogZslknRs16sM8ThT+VQanQk/xaAHectvCnoAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Totem.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAL0lEQVR4XhWHsREAEADEUn75nCFsobWV1tDO8SlyCUFYrBO3Tp14U/QjazFubIAHe8QFDv6AT7YAAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Trophy.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAP0lEQVR4XhXKsQ1AERgA4UveC6UR2EPCCFawgQUMZxCFEUQhCoX8yeWqD+BrqIwe+E4NpCWVTbzYg5kCfieHBzK/DMQgKfdXAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Item_Tunic.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4Xj3CoQ0AIAwAwXcgCMHTMAOyipmQCNI5kYxCargcX+rUgwp7YObzJFxioS1EcTyZQgadflxIoAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Urn.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAQElEQVR4XhXKsQ1AQAAAwOv+dV8ovnqtDVSiNIY1dFYwkGFEbQAREdEfhF1MqlXOutNcLK/hMd3GQ1vrN831Mz4CMQvvpUvIHAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Vegetable.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMUlEQVR4XlXCoQ0AIAxFwUcQGIbBVTAYltH+IIgOQJiBFMflCCLNWBt9Mc7XNsXJ4rkqcgzcpTjdBwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Vial.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALElEQVR4Xk2HwQkAMAjEAhb7k47Q0Rz1RnGU4qcY8kiYmPBkV8e6xPn2moAHYQEEV8QFhT8AAAAASUVORK5CYII="
  },
  {
    "filename": "Item_Wand.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANElEQVR4XgXAMQ3AIBAAwOuHpBupAIbKQA4SGBk7Ig0tTEhowOPCYEuLKY5I7k9+FSqdBj+JgQWZio6FVAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Item_Xylophone.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4XhXCsQmAQAwAwENEvrD4ERzBERwlNqk+O1g5j5XziXBwTLZZb1qX+YtFvepRt7E7LysBH6SPB7FiAGqjAAAAAElFTkSuQmCC"
  },
  {
    "filename": "LICENSE.md",
    "base64": "U2Nyb2xsIG8nIFNwcml0ZXMgYnkgU2ViYXN0aWFhbiB2YW4gSGlqZnRlLCAyMDEzCgpUaGlzIHdvcmsgaXMgbGljZW5zZWQgdW5kZXIgdGhlIENyZWF0aXZlIENvbW1vbnMKQXR0cmlidXRpb24gMy4wIFVucG9ydGVkIExpY2Vuc2UuIFRvIHZpZXcgYSBjb3B5IG9mIHRoaXMKbGljZW5zZSwgdmlzaXQgaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvYnkvMy4wLwpvciBzZW5kIGEgbGV0dGVyIHRvIENyZWF0aXZlIENvbW1vbnMsIFBPIEJveCAxODY2LApNb3VudGFpbiBWaWV3LCBDQSA5NDA0MiwgVVNBLg=="
  },
  {
    "filename": "Other_Arcane.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOklEQVR4XhXKsQmAMBAAwEOfYPFFRtAmtSPExnnEKcSpHE0CVx7Mn7zUxxbDUfRXv52TFtZQF7mPxg+PsQWSUp6DzAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Other_At.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMElEQVR4XkXJMQ0AIAwF0du6IKAy6qnJl4YKxHwpBBh4ue14wmRSg55Iv14UZ4W5Nr28B/N2OQ2EAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Attack.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAPklEQVR4Xh3IsRFAMAAAwD8Kp2EBZwJlCoULIykVGcJIGcUIypS5S/twT55VimKyFOOv/wzZ/DqPhrstuDpU6xEJComG9gIAAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Confusion.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XgXAMQ2AMBAAwEu6g4EGNLB1eA14ofhAA1JQgBbGHzoQKI/5s6YIrToufddf52IbWqpMlBs/CXcKYEa6zhkAAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Dead.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XhXKuw0AEBgA4UsUJOJVqqxkFGMYwRhGMIoRlEr+5GsuOQC9CYdyRR6kLnxDLWzFRNz8jyQ8Ax8KE6tFXCIAAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Defend.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAKklEQVR4Xm3CwQkAEAAAwCNK+fh5soEVjGZsTwuog3HNZP30ojZ5ils4eGX+A8PpHr7lAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Divine.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAOUlEQVR4Xh2KsQ0AEBAALxLRKfUiUf8IXxhAZQP7GcoARuBdrrjiANSRG16/3ZyDcKhCWkSxLts2uJKhByi0g7DwAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Emanation.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4XhXKoQ2AQAwAwAs0obLPBIwCFvkjoRizoxD8wfk4wtqiZBptlv02XpWybP2Da8EHkjkFtNjg4pUAAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Ex.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALklEQVR4Xj2IoREAIBDDcofAoSMYhLEYkVF+FGogV5GUjzIXY9OLdrJIMifK4wJ+XAVZLTIorwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Other_Fire.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4XgXAMQqAIAAAwAuitqLNH7QGQmvfaRRnH9HzmsKHiAQMbI/4is3erN3VlU8+3Ys0OUYhmCt+CY0Kgye0zj0AAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Heart.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMElEQVR4XkXKoRUAIAgA0fMZjG6Ao7gWkdEYxRGMBgMN7v14ZKLsX9ZjXsahO83yCvCrCcQ8a9eqAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Ice.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMElEQVR4XhXEMQ0AIQwAwCMfEkYEoKAKGF9EBVQK0gnLAWbJsslhBotgaPTfd54NLlc1A1B0iLocAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Lightning.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAL0lEQVR4XgXAMQ3AIBAF0Ed+U0Yk1CrSkIKEG29sAGkp85rH2lb7yrjGkS28PPAD5hAIdGK7QH0AAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Moon.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAALUlEQVR4Xj2KwQ0AIAjEahjAEVzVURnhnjwVSGjuc2lp9uU4JpYgZnlNX2VQPP2SCsV33InNAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Music.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XiXKMQ0AIAwF0SNpUiQgg4GxgpDwJSKJkTZc3nhUA0S7eDp4x9LGxBIxiVp+D59SBccuAjgGAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Plus.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAIklEQVR4XkXIOw0AAAgDURKE4N9FZXVk6efyppu0kGN0ugfSlwjvwIMluAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Other_Poison.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XhXCwQmAQAwAsLQ6iGPo35F8OlxHcYwicsiFgBafZcz5ynSs7nZxspd4xEbhBwVuCht/I7SyAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Sleep.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XiXGsQ2AIBAAwPvY2NrTuAVjMcAXjsYoTPIxhOSKg6hNo8vhXp7ylgTX5BMnfuPXCNiezd24AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Solid.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA1BMVEX///+nxBvIAAAAFElEQVR4XpXAgQAAAACAoP2pZ6jQADAAASe/JKQAAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Star.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANklEQVR4Xh3EQQoAEBQA0ZGydQHlGlZcxUEUR3MkSwvJ/6bXAJih7FT9Ug5x45dc5UYKVMfvARmYCvl5sYGWAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Sun.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAM0lEQVR4XiWKsQkAIBDEYv/wI1ja/kau4rAOcKVYySGkCCQAbVHB2KTox8xrvqecKrzBAyqZDJ1WBHxnAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Target.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xg2KOQ0AIBAEJ0EABkiwQXGmCD7QhAK0UF7JbLbYZ1DlUB89iWA05mZdbbA6egmIAR8YXAvLZj5YaAAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Other_Up.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMElEQVR4Xl3HsREAIAjAwHgWlo7gKK7maI7iCJQUFHjQ8ZcmpHbol/GYwlK2/a0FB+4sCg+vzLDkAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Other_Up_Right.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAL0lEQVR4Xj3GIQ4AIBDEwBIE684iSPjJvZunrYScYERTvjDDdNNe6+OwJykWiMIFx+YHXbaa7l8AAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Wait.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMklEQVR4Xi3KsQkAIAwAwUcsIha6gY7iiBnNUSwtk0Dgii8eYP0gM9VNOS6iKf0yXj5golQH5GnlsvcAAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Warning.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAANUlEQVR4Xh3CwQ0AEBAAwRUJPyUohVaU4OkhR2lKUYiInMkAmIld2m9cIVQdm86H1BFhXL4H4PEJ6yRYQX0AAAAASUVORK5CYII="
  },
  {
    "filename": "Other_Water.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAL0lEQVR4XhXCoQ0AIAxFwQemddQh21EYDYlkREYhPzmAtulLrGRcySPTCcEDe8AHeFcFLlY709QAAAAASUVORK5CYII="
  },
  {
    "filename": "Overworld_Castlle.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAN0lEQVR4Xj3CsQ0AEBBA0Z8obHAaYgK9zjo3oEJpFKURFAq5xsvjK512LZAPYSNKrDYN3MQv4AHHUAkTSRoyfQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Overworld_Cave.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAMklEQVR4Xj3JsQkAIAwAwQcLSxdIdI2M5miWGcURLFOKEHyue37FqZt2nhH0iVjSlRcuv9gI0WHbmRgAAAAASUVORK5CYII="
  },
  {
    "filename": "Overworld_House.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAO0lEQVR4Xj3CoRFAEQCA4d975wRNkZwRrCEazSiiaAQjiAYQRKf47uMRmS8hC7pjJ2HhNybervI31AAOsL4I4PW7+4MAAAAASUVORK5CYII="
  },
  {
    "filename": "Scroll-O-Sprites-by-Quale.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAAUAAAATwAgMAAAD4DHHrAAAACVBMVEURETMzM1Xu7sx4rdQeAAAgQElEQVR4XuyTMWrEMBBFhyVufpUmdxB7GhXrxqfJUaYxmDllMl/7QRCSJlKayMvjaxnPYyTbtq7F4t9xex+igWdgnLAUCW2UsBQ4OCmuQUIr4KRl2IQX7H4ZGSCkktMNGREOx3VzuNndh+yZsVgsyL6TTVmNqKbcGlrXhPXpQhWFhKophYTiD4QRNYHSzRLVlHhiEYYIT1ifLsR5OLqfhLmd/Mfs7mEx46zsnSjcdl44s5HiH4RNmvTC7G2WOkX4iQ7ct9oLSQT1OvwvwnD2NguFb3T/VkjJg8LX51Eezi2xqa0TPTDdg/a6VDtOCrMneyl5mSmkRNv9Rtjq6YH3QtanCy2CpLD/rFRTSphrCiO4Hi38YO9uchvXmX6B/5/CG4Co0R2k54RGBFdxBs8CepAFFTwStIqCRkSt8rJI0U63ffNhCe/t05CMCmUn59dFSuYRbUq6A/fGvwM8wRP88drLl/p/6P/8sx1DvNY1/Oef58A3dKMuL/+8dv4VeHk2w9f/vvysjItvNafXluvby88fNerPn0+AlWrMj1rR//zsufYq+9ozGb45+Apn8OqNsA/8n9p2bwPs9E6wcp7X1m6jDf/z09vwCRBw4g/YsU/wBE/wBE/wBOtxwhV4OQJ8fT0axA///20/cnlra287wZri6w8vXl/wWtdesRusRzNo4ccxNfaBfWnli/PA686t3DMcxy/epn/mjn2CehQYYHoFaV3kDsjlEzCX95G3klpp9h7qIfQJaDYibIER10Vuf0eAfA8UuuEDVRTY+kVwWT1ijeBB0yy1nNr6sgpYHVIsBqwLKIYvZRhGUC5yXTeT3nYmKPhihsoeYQSxynW9ZME0A1MRqAIld9AHpj0eZyhm4VEbBrM4MuQV6tl/DuYCySWBS4aXDng51lNCyCSci7KQktAnVRZCFK8cCWpZg7ay8LIqeEVYFjiUzQrl8jFIZjLVSIsVshZL5UuLdRFEBmlvmmSWAhA/BL0qNUJaSuCc/PlcAy1SUlgBWWsGEIlEofBF0IEQ2vNUYVBo4KIN7LB9DiIlj+AIcgrbc8+or7OCLgGkqYH5cikfgzGAYohewiy0UrmvexkiqCUV++vL+if1h9P8b+kPI+TL/SGZSQ0vZw8IjXUPgTKQSMjWGiaf7tje59WINeYW0+zPp+25EKsgm9BiMq3LHGKIX8kwXLPKRcY6mylyQXDQuD0vQP4QnEqea4StnD2jsc4lK6YZNBWZCitKxgxMH3ZfnIsuuYTtPdza0MstWoaUF+GU4NlHofAhCFYIawJrrpEc8NKDWRUNmgSsrT9kZf30fwExVk1YoNz6Qy89onIAr6DFAOXeH7J+vttEs7D1h7L1h9KiIogBpAB9qz+0a38Y3vWHvn7tvvir/SH6f+wgkEKAIykBoLC1562DNRPP/fn+cICX4K81EJcLPgZDBIUYvYRZaOXoD816ZhRwfX2av9x9BS/SYYNHkgA2JDLxch946wslsOn2/EnQscutDwy5xLH+HOhQSRjHNXEryUyeB5cLcLkEAiQ6BnifuAO0ixOhdV2AeMlPZ+g7qmag5EApyVQxL7nkdtj2SXxwjB1ywLJiqpiXnMtzIDmQC/KcEmJAygVeMq/PbWXORUlIklAiZcn9IJ6i8nNgBZTNNC2rhJRiBXufaCU+BSYHc9HWH86TYpq194mangJjBzRdJIR5ijH158ghPwemGUgJaU6t64p59Iemz4HKfavGEKCMaNaeg+0vG9Gf4Ame4Ame4Am+/+TfR4O7wdd7YP+3FT/69ylvL2M+yK4q1ykwlezfWIzZFjvAgdS29MchoGfo2Xnt94M1M29DZ3/Uh7fhPvDhlv6zwP1xgmQmXwmM8jOQzfRLwb38FMxm5UuhvTwONNYvgYlL8MjZ5swlpWxhxHswZQ1fG+tlS1vMjjg6ov1DSyl58X9MQyqr3g1vPwK9dHS8lqxs2ZX6vDwCn2jDst7WqYTPq6woeS2llYXeBWpYXzfuvzf+2lZ2YMCjHMDIcMTXd+xCvVRs5fZ8La0ccdhbb8T/Vudwgid4gid4gid4jpeBP3G87KM7H+UdVeV/sE3vOy7DNwdf3g4DnfM4MMM+B/Hfu2OfYIhfA6lEEKugDECA1B+0WALNmNY5IssXQbugzxPZPBNgQlVspmwzsoGzKYp+DhIgsIKQS6TcPRagIqWFOWRSQ2H2MUiSEGKIxBYbiAiwSXaETUOwSDYmVayRvgKmuiCatDa8iGemFSyBk8aK0loqeKmggNbPqmzSQTJNl0sCQgM9q1SxaGjrtAh4ESHlj8EpKXJKJfQ5dDNYgRJTn+JnmNaLhEJKlxV86Rvt4/k2VkLubRSxLoAQ0rrMICupXOJUUsyZZ9ILscqFzD4GPZ28LhX0Kq2KXCo4z70doVws5ktJVFLgkgPZJ9MFkS3m7I0eEC+X4GCY04xl3Uaq0KwoZAjcoujHoFmcQpyDqXjJ66IhePPZBq6aC1XQCtcIn4GULUYgIBsoRMnLWqgSmCfwRQpnarsQ+m6JEFL6tMqtvMxCgExCM1lWCIEJgZODi1JeFObZB3wNDCaORKEQWIAYEAgIiTVnVl7mmfM806fguxkXDgahOEVTsG5gqFCYo4Q51UAI/+oe+wRP8ARP8ATP8fJLfbz2Y5/XnaAjAwQOAf275Qa++vejL2+7Qf9uuYE/K16X/Rmigz/+OQw8PMN6pl59VNbj7S/esU+QAAgdCQqIVQ4Br6c8mB0CdsgMHrtBH5ZhWceM+s+Azycn+1DseuqDmewGYYZx1SyWST+ZLv21SfJZl5KVS16o7AeFWjuOOGSeg7fgiN1gm+lslkbsBkMuMZqFEbtBTunYDDlETcppxG4QIQIxjPirO9gTPMETPMETPMfLr61sF68bR0R7h2Y3sC87QZ9B7GAt8fJzjJr3ZFgXByvVnvVXdoE/3g4GX3EDX34eAPYr9NXcfjrXR81H74dPZnjU5QDPziFcAVYkNiCX/iLb90HK5ZfrNWQvzZD7a8+dzDtKzkWjGWg1CdkcfgK8OEjioA/NohBoWfy5QOgZcO3g5YIIhIlEJltnUlIC5MkqExz075cdzGsuJFCK4ftgKEuHS0YoOU4pSVYupNoy/P75y8oAsoAVHhOrsLI+D8YQgAxwBC+TThyFyiI0kz431hMSwEBCY9zcJyyLCYPk2+CU10iLiQ9zkQv4dmJB+923wVihkE2ZpMVkpjCbkSVGK/G5M/2jKnOP6JmyaQPsmbdeSoBIHMPbmK0B5EC2J8AwOYgrqKtcAV//WzrYEzzBEzzBEzzB2/1mjgJfX48GMa4F+/ra1t52gz+qhO1asL66F3TSz63GOIt5L+jpVayDPrQ/4Kq/3nI+Vu5nMf+NO/YJEgLoNpQNtAHy5PAWSI00k/4sAnlSAHvAFNisI1FrIDn29AA8AJElK9gAakiCWQLJ90EykUQlZuaCXKQGIDFhWZMPyL8NsmlMbCHHpcAMKMvIMOSUngSzdlAZNGVkXiKEgmf47eFtMKngog2cJxBIsi2RAX0ORIiZc2ltKASKUwVnjWZIuaRvVzkkxAgLWXKhGGTLsIFRKHwfVERey8xm2maMC8HBZIYaT2SIS8ylKKtGVlaOQXeCiNEiSBAcmLLOA3jqkyUuiFPmkIIqlBG5BAgBsYby98Esa+C0alrX0iAQSEigLKT8F42XT/AET/AET/AEfeTkNxnzy0odOF52EDgGrEubj/02ZmPvrnK/r9r4GviADP900L+h9/nY4yzmo/fD14PBl59/f+eA1W4PvSyrx2q82m9LB6h8CxS6XDwWW1YB6H1ks9LAZXVCIREw+xhsOSiQzXQxW99HBIKDPvRocEggQD4GVcGFJNsqjszAdDG7LEId5LXkZe2ZckAgiR+CF1VdCms2TQvQQDGjZbncg1kQQwwfbmUSKFeQTDoY5klyoWV2kMoNRAULlJXvQE9trWEKAilISYqxLFzWeZomYR2gYyPDhDVDST4CbZXWgOr1WR1sGZI8AmeUWRT4GNSlXNQKrbaB03QD2TEN0cxBJYEUID8EFaAGcsFqBWyLXjMM8Rewp0SFhMTb+SHoi4OtDa1otvXWhjHQsmygIMRtowSzuJotH4IkJBUs2Qpft7IQ+X6Ylw6OjRKAmMzSh+Ciq1yspArm644NXAYYMUD0ATugH+6HrAoyBVfUwYF6OUD0JY7rf33YOXiVYRchW+VR5zACQPAqf9o5KFhHPO6+buHZ/S/22CRXwKvEZrrr8v6ODGwE56LPgWbHgmQmCUgDjEDwMgDxOVBZHBhVn2IHyUyezjADZVR9miSMDfMcKCQODNBjgM9d3t/sWmVfIhAc2w8CvcrzMg/06TYcc0amdWrgwJ4HSQBlTJbLyPb5DJfcQaCBrbrAjgxTuoKOTWWeHfQ4pHM4BBwxtvT+7svM4/75iNtr/x9Aq8sN8OW+tHfLHwie4Kfd16Z+uvuM55+CU10aUguYTbGt+3J7XqO94OWnVZ7r0sBawCzMbd2X2/PZS1/uz5Y7M3xiKx8NnrNZ/hLwBE/wBE/wvB7sy/b9io8Kd17fpserxzHXt/FvUgbYz9lrj7enwH4vesca2pb6z/jyZIYV2s7Z+wn4moN9LuJzYE/wdYCv2M7Zq/rTGfq9U1Ah38rOeQt6yz4B7r/hyfHg2TmECEIYwN0dS74NUoiCpfwCJiCN+DboWVDk+T0YPW+z4OX4NHiT05cypKCxSUGdQAwUphDnBgLi8S0wT0kayBFIjJj4BubSQOqAfArmbCXoJSKXnuEAzW4gF+kUfW2jhGWOI8PRhtcMU+pgdCB8PrylAAnTGqdpnhH0AegZBqHZhGyST8FsVMKFYy65tAxjQIzhtyonYYIyRL9QZQiluWAsmhA1jQyvbTh29K+1IUfputyDfQt/HWQznTTIwx3bbOzY38sQeT3urYcQgQh5unM4O9gTPMETPMETPM/XA8a0wd1z5w4H2wj57fV//KfPQzwAbGfq/dd/+iy//aCPkOHgK44AvcLw4fZB4HZFm+o77PMQ//Id+wRZAZIbkMs9EOQboFlH5wlQfXxrE/oGSGbSsooBzAyYSc/6grAuMZsV8DfAMQ4hZfnlHwjT+F1A/hLY287BkWEDy9YM09JBQeA8fwIGjwJMM8Y0GYTYwdWkgcvaAAdTvnwGztex05gJlOepQFVpMfXnlMuYhRZihnw4vIUI0P8UWbmM65syM8AVLFmCWXTUaxAT0segB4fehvOkY9fxhRYrpNyyo5QERiVG6OcbhbdyXW7TZQDwuoEhipcopSSiz8ERY0sPMJffQKOSi8l3wFupqhUMtC4yAjQhm+Fb4AhmRi5FwYprEIGtPNE5sG5VplJVXAP32NnBnuAJnuAJnuB5/5QG9CvC7gRf8SsI7AbHlWDb98xv/TvRPVXuF0N1ttov4/qwezJ0wkH/FvcQcGTold8N+lb2NtyubvNWy/rYAR7yZfDx4Nk5xG1cQgITAAaAb0Au3wWTIEQHI6goCAJE6dikELoHTD4AowHT7GAAskYHSToYkXC5APwrQKY9czK5B2GAMgAuNSRsGbKt4iAJCSiDFEACkLU7tgLhEUjWBodABkAacAFMJNuiDnIuGqKBC+C/gibAspIVwVTuQeKL3MYgWkEDlRgzdzALlQykEAB2UAoIVsiSYNF7EHlroIsCpClAwRYAARxtg/JUQTaNZoqsQKngqkJZHoAxS8ol0SoASwrBGpgXxxblilCScgUltIaki4N4AFbAq8wKICOECIRSQe5g/56ZSgikfCGl2YCqkolQosfnSXlkA1AcvCCggtbBmEvIuBQuFHGhyLNJyzBFIYQHoAJhWWM2AWkFJ8h7MAjFfCk6dhu+mHCRACEQ4j1I4ii3DFkAukAI8QryWuNiGAubSba83UhI7kHu1e41BwCCwOSXT5toMXkHIt/8ezChL1nHug3r1sZcfnnbcTk72DuQrJcme8HR6F0i0xqyE1wuAF2awlbAZPtAyiobqFwSGCL7wWBgB9cKih4AsoDNhNcVZNamwHwxHoPkDzNlZQlh3gmyCFLqVfYsBTs3CiAgcXCr9rQPhBA8w9GzOLp7x2Yh7esG2gt6MKB/TOdwgid4gid4gid4np/yOs5O6UdAr8+CLo3idnbKTrCfiTLAfraKw09/fvjalnF2yo9+bsrPHRkO0BGXHfzxz8Gg4zvbcJyd4s89479rxz5BEta7+0r9BigQWBpA43cMID4ES2Qvc7xinG5ockRAS3YlgMsABSR4DEIBmIzbQCGXLeDRQL4kAYrSUhTZAFoUrI9ARgT3uqSkJOZoh4v2mimDFQpehZSUzAS8KswegQkRELAoVkuUslAxBRvI0dXAy6p9Ls4iUBJ2MBfQOss9yIqYEZFVsRg4ZQ22FlpZHKGSJedSgi0KywIuYCGB9b+9By0hRglAEcoFjBzzaoWKCSdWEmogW1EUA0jB1C7uBLZyD/ICRJZAmsBWQSkyWQkNLBU0a6CXtLUZLQsoX0DrInfgVCIiELhsoJlG00CWHZQBenZkBaBtj2FCMIt3YK5gAlLMEXlVkC0S0kUdDNluICvYamwgEB5fdy6p9MshMWrpoApxQIUc1HG/M5CADeAZQBZkRNAa78EsHSQGYl4Ar4ZENMhUrzs6R2QFaIAij0EmtHYLAUg5ARwjonQE2DAFgkvb25f7xsQ64Q6kgla9qNc+QcB4sMgAb5OHcvk39ofxUR/I+jyIbL1M6YaltAPceo4WA87leZDMZii3LgqsDaNllT2gOJiVi2fnaADiHlAdjWbhOt1SdoAwS5yLNpAVKAQuiM9/3Ecys5CmCnt2pBC2PaDGeZwG1rJTRLY9bbh2kMykgbIf7JgZjgL713BjgwCRjORpMCn1rjwGeJCQ7HrrcS5jDnEPf/7FBM/B4wme4Ame4Ame5+v5rEM/n+uoy/s7+OI/jwL9bLgX+NzDw8AX/PjHq3wg+II/F9zuFgD/+Xfv2CdIpRfmZeqAtoIBTe01Tr8qQT4AuQDk4AygACagoDADK2s2CQCF38C5hj4ASYDsvxTAAkAKMkUg7fMeSgSrAFEwDvBB0sGc7kGmDYoRSAFgaWBEw9gQA60ALgk25kHkSHEpQCoPwBmgEgFJQHAQ4BIRSdm0gYQZoBAc66DFKVoJ+ihDKHqVpACXAIg/jwhcuKCBkEkQolxBMkwxhpweZpiAfAHCRUE61wCyKCgXXiV6IC6KeMEVZENeWVN5lGFewDkAaRGwpBrbJEfTK0ik5MmTgABBrqDlysVwD5YKpgioARkAA7ACpCysiF5tBCgnd0UaaIYYcknlAUhrjUVAUoACQBwUoPBtqBslptKzo5IFWcBaycR6D87bdoGCFD1KLxkbKDG2f1ioge1RnATuQQcykACw/BoESAMRIpbxeTYr2rRP4CHokbiDeQveyr4jk9MJCe+WjrH+v8BRvl//dXJyQvwVZP37Oli250FeF/0V09F2ICH5FsglD+y2W8TQ+71SEHKJ3wbHR/C0rOLZNlQIVAwB+B7o4SCbKQs1jOdJ+9vM5Nsgldy6pAiErFwq6Vl2cBVlQANJZLPyZdCzavf2qA+U7M3QQDBiawZWzVLCl0CkhAbOUwOJRNhsa0NE5IAwTzF+FfT26hlOLTuvvme9fTgZYb2nhsxfAz2rsSGQSwNBAloXGWBbMum3QLCOa7c1tL2mEAe/tZXHed9jA8EMHg1MBCz0fOdAyjJwFlJw60WP6RwY0A+/aDgHjyd4gid4gid4gj9egTHn8NALbh8Gvv7XZ871M24PAjGuh/3zqAzH9bD/OQb8n9cjM3Tw5e3QNuzqwTv2y8+d4Nk5CED3Y/9s26CSMW6kFiEBgEQggPUxCNoCv02TuVjJ2WbA4AAJuRYJVaUYofkxCGRpQX041sfKCViskINsmMbt8bh4toopgiDyGIQpUGbQpZ+cmxIqBAgQWuLcwJhi8PwIEAcDIT4Go8Ya4mAwjV5lNhN4ACDdQFCAQCiGCk4fgLREtPQtNpAVbEUgEAKBJHeQJBCVysYGRkLCY3BWBAOI1UE209bg2/RAulgcbTgFam2XpilFyPz48ly8CAIieJaQ5w1kgVLP0CzmCk5CM4U4E0GQrQ2kH4MZoW9o+EqrcgNHhqYRAGIugUikohISIyaEx1UuHqGVIYTYJoCyAeOq4oaWYQISoW8USgtCQnwIkoYa6AERsIJrwPrZ66R9a2ahAiE4isIIeAyC5RYQgoNkQFISf6dQthhSiuPtx620Bj8E8y1uH0+tQDQT2sAxp+n61uMSoYyHYBrxW+dQgd7qFfLsolmoWiAAH3UOXw+Sv6SDPcETPMETPMFzvHwc+HZwhn7V6T7WOwwcZ8AdCP54qyCAw8bLaOPlw8B2R676+Jt37BMkcLkCadwZZwcYCtv1BKA+jBXalWEBCbbRZ2zZ5bIHZKGgG1DQslvWPWAGhSytymxIdaF12XPCS6mgRKwRZBto9jzIphWcGxg8QyDB7PnL0WQTBxUrEKggrUuiXOR5kGMFF2lgbCBI6PkqT9AbmGIFZV8bpouDBihAqKAydoE530BIBftOjqdBXgTEpYNZvNx7JhfAdgPS2cGe4Ame4Al+L07wvJ/UKw48neRosJI/+mgPL2+HVLnfILldgRoHgHDrvx38cUSGFXobIF6P2co1w3bX5dqSu8FOnp3DvwUk8fjtPlMkoOvvP7h8K8lDkAGFye0ccWQhuoCQgBABNrkDSUhaBmatHHP/HQi5RLIC2n4HMmFeZYpXEHcgA9qyzBuoLGymDvTMDKx8/RtmUxYAOTy+akfiOfUqdRAlw8Fx5yaQgYUUKQFZJWTTKUI6qA/AMT4mk1bm0kCPBsIkkxSUDGQIzAohzLALYPIY7FXcQFYMbDKbG8jawQjhCgKkHTR5CDqCfANbaYb3YJ9SnSTrWoAwk4kngP83aMu1yo45+r7KHcySAycA4iDo4UZZtGdF143i6ADHRmntWsEkKCCAMgSkD3cbOMQF192mP8/6frfx57VEBhKm6KaABQ937A41uD8naVm937H7RPCWQHSog4/feg2C4O4ezO/fem2/lJ6AZwghIH23t3nfOQC3BGgr47+wPxzVMQH1OTUZKGOXeQ40A8i0gWbIQiUA8WmwZcL9/elIVi7BECGEp0BW1g6yOMgl6z5QSBFszppBl4uQmuwCW18XEFALIhFcDA2M4UkwxMIXRCIrDeTSwRAH8M2P+4KW7NUk23pl3QkylRybg94vXvZVmck0jmSWCWyslCG4XJ4ExYRFe3ZCvR9cqOLrcyDpOFNWgHXpHewUALPnQLhF4dolBeW2QZ5/L/M4R7FHBAJIvgyeg8cTPMETPMETPO+vdxz4isNBnytyP41n5/WxD83wzwf9Q9OPr21zdg4neIKsJKysKLmwerDuAlNiSXWhkpCA5Ms+sJCgWpwOAnMiISVNKWtWKCuXnVUmYSDl4tlBa6TdYEJjkuO7Qdbtg7yU9brFj98PT/AEAxBJ2toxIAESYogA/a/0h1k9+vslJVb/mZCTr2fdoiRfgv/wvxuPXO7ANBaktk5C4mAnRpDcQLg6Ao9BbCA2UCs+55uHDZw9e+iNewhmdShLllRycTCLg6kMj3WAJH19gFnuwFzeZZjeZ+hCVg+kATrHyKU/PMMvtOEkjQ+NwK0N26ZxGp+04djKCVzaVvbXioOsCay9yh650bfN9Wgrfxof9t9ycOdAB4MjTjCSAOGXchfYezb6rfyTquz94K2HS9uyA0ztMaA/EczijwH99VW+38ojzs7h9zjB8wg2bT9IvSAhSeDfCP7OEewAOW04HoDfPYLlUgNc8tZvM/I4ei2pcLk/gh1xByKNJcvtcI7RiQYkz/j9Aef7LuoO5O34MBfGALNUYB5gqvgASfwvuPRHwofH2Dcw6a8gkoPbRxwD74EHGb5vw3H4S+rg1obISrUk4VgFr8t4PGzD95F+n8OW7o4PWb98fDj+mPE7eB4fnuB5BNt7tQOPYDtw+NHXn3t8ONrwbz0+PMETlPcAya2DCPFbIEcGg5W1Q6xXUBmkPGaU+6IAfw5O/ROueUDkhITgZQ9UnQQjPuttkibEkqSD6CCAwYUI5QYxcoF+miEJlymNqlIr34Odbp2cA+nTDDklnRKl99CvIAP6jQzTXMGa4wDuwQSkL7chR2j/nPAd9huoAH91K/dw7m5fHLvN2TnsA81KmWeiA8F1naYQDgSXZZ5jPBDMeZpEdoKs4/FMGyoKgQRCwtqPdGKIxR+5PNGGFJAYrFCSnGLwR7XNH2ZPtCEFnnteDk4lhqncwCfacNIojjlZwbCB1Lkn2jAgCoMEylrB+VfwiTacwBgbJaUYto0SYmuGnfuhb+Vejsf+/fB8L+9sw3O8fIIneIIneIIneIIneIL/l107WG0YhsEAPMF0Xw95H/2H3f+B/f6vskmy20AuHs4uQwbbSlo+5ASLGto32wW0vdzkAn7uJfj138ACCyywwAKp1N5NAY+9b4IAMMfsu2DHk/UQcgNoYko1ab74uzJsx8hwGwSQYI7ATW/ZQf6M1Nop0Qos0GRGvALIIVs7lkD020HI2MLiI8CYqaaU3hnVDEJdBO0wZJHhKNKIuY+7cQUDsAbOmiovcFxJgiYABfGsV8HoEzwneA7Q1zMcZbDFSLWcIzMvjpkh9QTWTimwwAILLLDAAqmvuB3euQdeT3Z0eAN8/rABqBSqySYImMzzKHaXnCAeJgl6drtLhoPoebTt2AapVDyo/n7zabY6LxdY4LkIcsQZmfIE8HcgkOCMGfMWCFDZqRGLSYJUSp6V/Q591mWwg6MUGuaS4S1Gjm+ZLIMUxnnYBHPJg5hg0I9lMICIHWzHBGNA3lkGqVRKU2qCTdth2uKujaLo5ZG6CHpq1zY/wZ07hboG1l4usMACCyywwAILLPDv/4zXN9t3u3ZMAwAIA0CQAXYWfDFQ/1ZI0FCm3gl4BV9yuRQUFBQUFFyR5rxgS/SCkehDsA4AuJW7Y7xOafkIAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Wall_ES.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAI0lEQVR4XmXEyQkAAAgEsXkLsv13uR14/AQhhKplHuHAedZo0igRgrpBRuEAAAAASUVORK5CYII="
  },
  {
    "filename": "Wall_ESW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJklEQVR4XmWIsQkAAAjDOgvia57qaX5Q6+JiCBkCcv10oAzpVx05+akJ4mrPjkMAAAAASUVORK5CYII="
  },
  {
    "filename": "Wall_EW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAIklEQVR4XmWKsQkAAAzCfNIn86RFCl0qwSFESXmrBNn3Ww40Cg9HuNwn3QAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Wall_NE.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJklEQVR4Xl3EsQkAAAgDwTQ2Nk7nkk6XDVTSCD7HIyj9bZbwuqsBRykKyZc580MAAAAASUVORK5CYII="
  },
  {
    "filename": "Wall_NES.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJElEQVR4Xl2KsQkAAAjDMgvF/7/sCUIFByFkCMEdeCQW1nnPAXljD4TVBU9VAAAAAElFTkSuQmCC"
  },
  {
    "filename": "Wall_NESW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJ0lEQVR4XmWKsQkAAAjDOgvF1zzV03qCFMHFEjqEQGneLDtQvN9yAKDkB+RPMPE6AAAAAElFTkSuQmCC"
  },
  {
    "filename": "Wall_NEW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJUlEQVR4XmWIMQ0AAAjD5gB1Mzl1OBjj4aFpehRd68eGBPKaEwfbNg1JWcnW6AAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Wall_NS.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAGUlEQVR4XpXCAQ0AAACCMBvYvyURyMD2nUR3tw/x+YUJpwAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Wall_NSW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAJUlEQVR4Xl2KQQkAAAjE1uCqGdVoF0HUhyCMPcawGh4TU8R5zwKtSAhRbaOQaQAAAABJRU5ErkJggg=="
  },
  {
    "filename": "Wall_NW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUDAwP///92WDhNAAAAJklEQVR4XmXEOREAAAjEwHOANRr8UaPuHPA1FGR2AuHIpzNF+H0rFRQSHDvBiiIAAAAASUVORK5CYII="
  },
  {
    "filename": "Wall_SW.png",
    "base64": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEX///8DAwPloG9eAAAAI0lEQVR4Xl3EUQkAAAhDwddg1YxqtDVQ9ifCccwE+ixa1NmxBhwKT28mkGAAAAAASUVORK5CYII="
  }
];
